# Generated by Django 6.0.5 on 2026-05-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(default='bebidas', max_length=50)),
                ('emoji', models.CharField(default='☕', max_length=10)),
            ],
        ),
    ]
