# Generated by Django 6.0.3 on 2026-05-27 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pedido_codigo_producto_descripcion_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranjasHorarias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('activa', models.BooleanField(default=True)),
                ('max_pedidos', models.IntegerField(default=50)),
            ],
            options={
                'verbose_name_plural': 'Franjas Horarias',
                'ordering': ['hora_inicio'],
            },
        ),
        migrations.AlterField(
            model_name='pedido',
            name='franja_horaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.franjashorarias'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('es_admin', models.BooleanField(default=False)),
                ('productos_favoritos', models.ManyToManyField(blank=True, related_name='usuarios_favorito', to='core.producto')),
            ],
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.usuario'),
        ),
    ]
